# Generated by Django 6.1 on 2026-08-29 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL path (e.g. manage-my-event.com/e/chief-jerrys-60th)', max_length=255, unique=True)),
                ('event_date', models.DateTimeField()),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('theme_settings', models.JSONField(blank=True, default=dict, help_text='Custom presentation options (primary_color, font_family, layout)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDING', 'Attending'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('plus_ones_allowed', models.IntegerField(default=0)),
                ('plus_ones_count', models.IntegerField(default=0)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
