# Generated by Django 6.1 on 2026-08-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL path', max_length=255, unique=True),
        ),
    ]
