# Generated by Django 6.1 on 2026-08-31 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_plus_ones',
            field=models.BooleanField(default=False, help_text='Allow guests to bring plus-ones'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_plus_ones_per_guest',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of plus-ones allowed per RSVP'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom presentation options (primary_color, font_family, layout, page_bg_color, section_bg_color)'),
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDING', 'Attending'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('plus_ones_allowed', models.IntegerField(default=0)),
                ('plus_ones_count', models.IntegerField(default=0)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
        migrations.CreateModel(
            name='RSVPGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plus_ones', to='events.rsvp')),
            ],
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
