# Generated by Django 6.1 on 2026-09-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_allow_plus_ones_event_max_plus_ones_per_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
