# Generated by Django 6.1 on 2026-09-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rsvp_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_guest_messages',
            field=models.BooleanField(default=False, help_text='Allow guests to leave a special message for the celebrant'),
        ),
    ]
