# Generated by Django 6.1 on 2026-09-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_allow_guest_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='about_text',
            new_name='guest_message',
        ),
    ]
