# Generated by Django 6.1 on 2026-09-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_about_text_rsvp_guest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_text',
            field=models.TextField(blank=True, help_text='Detailed host biography or background story'),
        ),
        migrations.AddField(
            model_name='event',
            name='about_title',
            field=models.CharField(blank=True, default='About the Host', help_text='Heading title for the bio section', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='show_about_section',
            field=models.BooleanField(default=False, help_text='Display the host bio and story section on the public event page'),
        ),
    ]
