# Generated by Django 6.1 on 2026-09-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_about_text_event_about_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
