# Generated by Django 6.1 on 2026-09-04 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rsvp_confirmation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_qr_checkins',
            field=models.BooleanField(default=False, help_text='Enable digital ticket QR codes and door scanner interface'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
