# Generated by Django 6.1 on 2026-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_enable_qr_checkins_rsvp_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum total venue capacity', null=True),
        ),
    ]
