# Generated by Django 6.1 on 2026-09-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_is_ticketed_tickettier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvps', to='events.tickettier'),
        ),
    ]
