# Generated by Django 6.1 on 2026-09-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rsvp_is_paid_rsvp_ticket_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='ticket_tier',
        ),
    ]
