# Generated by Django 6.1 on 2026-09-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rsvp_is_paid_rsvp_ticket_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='announcement_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='announcement_title',
            field=models.CharField(blank=True, default='Announcement', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
