# Generated by Django 6.1 on 2026-09-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_announcement_text_event_announcement_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slide_gallery/')),
                ('description', models.CharField(blank=True, help_text='Image description (max 200 chars)', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order sequence')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
